### ISSUE TITLE
how to switch VideoControlFlag_Trigger flag

### ISSUE THREAD

**Issue by aywhe** [wenyec/UVCViwer#1]
thank you for the code.
now a problem in front of me when i capture a still image from a camera using Directshow VideoControlFlag_Trigger. it cap the image when i push the camera capture button, but i need to cap the image from the camera when i RELEASE that button but NO PUSH it. so i think how to switch the tigger flag, but no solution found.
do you have any ideas?
thank you very much!

**Comment by wenyec** [comment]
It should relate to how the properties of the button set. You might to check the capture button you built if the properties of the button is set properly. Hope it can help you.

**Comment by aywhe** [comment]
thanks. i jump toward "libuvc"  and "libusb" to capture the button set and reset event.

**Comment by AndreaMontanari89** [comment]
> thanks. i jump toward "libuvc" and "libusb" to capture the button set and reset event.

Hi, i'm in the same situation but the combinations of libusb & libuvc doesn't work. I found my camera but i can't open it. What have you done?
